### PR TITLE
Add missing dependencies

### PR DESCRIPTION
**Pull request by Jebbs**

### CODE REVIEW

**Comment by collinsc** [comment]
lgtm

**Review by collinsc — APPROVED** [review]
lgtm

**Review by AdamuKaapan — APPROVED** [review]

**Review by AdamuKaapan — CHANGES_REQUESTED** [review]
I also had to install `ros-kinetic-gps-common` and `ros-kinetic-move-base`, so maybe add that as well? I believe that was required by @collinsc 's code (driver of some sort), does that sound correct?

**Comment by RyanBerge** [comment]
@AdamuKaapan Can't hurt, but for me those were installed with the standard kinetic install.

**Review by RyanBerge — APPROVED** [review]

**Review by AdamuKaapan — APPROVED** [review]

**Pull request merged**
